version: '3.8'

services:
  web_dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8020:8000"
    env_file:
      - .env.development
    restart: always
