services:
  web:
    container_name: sustainability_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./wait-for-db.sh db gunicorn --bind 0.0.0.0:8000 project.wsgi:application"
    volumes:
      - .:/usr/src/app
    ports:
      - "8010:8000"
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - project-network
    restart: always

  db:
    container_name: db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    networks:
      - project-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  task_worker:
    container_name: sustainability_task_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py process_tasks
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - project-network
    restart: always

volumes:
  postgres_data:

networks:
  project-network:
